Adding support for webp support
Girbons/comics-downloader pull request #155
Opened 2024-07-20 02:02 UTC by nbsmith

Adds support for being able to download webp images and convert as normal to preferred format.

2024-07-20 17:53 UTC, Girbons requested changes
thanks for the contribution @nbsmith! I just left a couple of notes before merging

2024-07-20 17:53 UTC, Girbons commented on pkg/core/core.go
> +			if strings.HasSuffix(link, ".webp") {
here we can do something like:

```go      
isWebp := strings.HasSuffix(link, ".webp")
err = util.SaveImage(imgFile, rsp.Body, format, isWebp)
```

2024-07-20 17:53 UTC, Girbons commented on pkg/util/image.go
> +func SaveImageWEBP(w io.Writer, content io.Reader, format string) error {
here we can reuse `SaveImage` 

```go
func SaveImage(w io.Writer, content io.Reader, format string, isWebp bool) error {
  var (
    img image.Image
    err error
  )

	if isWebp {
		img, err = webp.Decode(content)
	} else {
		img, _, err = image.Decode(content)
	}
       ...
```

2024-07-20 19:42 UTC, nbsmith commented
Looks good. Made the changes and it looks like they work just fine.

2024-07-22 00:03 UTC, nbsmith commented
Looked at the dependabot pull requests. Did those + the sys and text modules. It compiles and properly converts webp.

2024-07-22 06:43 UTC, merged